# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  module_spec_folder: 'reco_utils/azureml/azureml_designer_modules/module_specs'
  module_spec_pattern: '**/*.yaml'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - $(module_spec_folder)

pr: none
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/$(module_spec_folder)'
    Contents: $(module_spec_pattern)
    TargetFolder: '$(Build.SourcesDirectory)'
    OverWrite: true
    flattenFolders: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'snapshot'
    publishLocation: 'pipeline'