# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  module_spec_folder: 'reco_utils/azureml/azureml_designer_modules/module_specs'
  file_pattern: '**/*.yaml'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - $(module_spec_folder)

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: publish-run-experiment.yaml
    parameters:
      module_spec_folder: $(module_spec_folder)
      file_pattern: $(file_pattern)
